// try catch and finally
try{  
    var a=7;  
    if(a==3)  
    console.log("ok");  

    }  
    catch(e){  
        console.log("Error found"+e.message);  
        }  
    finally{  
    console.log("Value of a is 2 ");  
    }  